# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.0.31

pipelines:
  branches:
    master:
      - step:
          caches:
            - composer
          script:
            # Install library gd & zip php
            - apt-get update && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev zlib1g-dev
            - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
            - docker-php-ext-install -j$(nproc) gd
            - docker-php-ext-install zip
            
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - cd app
            - composer install

            #code sniffers - cek coding standard PSR-2
            #- ./vendor/bin/phpcbf --standard=ruleset.xml controllers/
            - ./vendor/bin/phpcs --standard=ruleset.xml controllers/

            #phpmd unsedcode
            - ./vendor/bin/phpmd controllers text unusedcode

            #phpmd naming
            - ./vendor/bin/phpmd controllers text naming

            #phpcpd
            - ./vendor/bin/phpcpd controllers
  custom:
    test:
      - step:
          caches:
            - composer
          script:
            # Install library gd & zip php
            - apt-get update && apt-get install -y libfreetype6-dev libjpeg62-turbo-dev libpng-dev zlib1g-dev
            - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
            - docker-php-ext-install -j$(nproc) gd
            - docker-php-ext-install zip
            
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - cd app
            - composer install

            #code sniffers - cek coding standard PSR-2
            #- ./vendor/bin/phpcbf --standard=ruleset.xml controllers/
            - ./vendor/bin/phpcs --standard=ruleset.xml controllers/

            #phpmd unsedcode
            - ./vendor/bin/phpmd controllers text unusedcode

            #phpmd naming
            - ./vendor/bin/phpmd controllers text naming

            #phpcpd
            - ./vendor/bin/phpcpd controllers